[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_port = COM9
upload_port = COM9
monitor_filters = send_on_enter
lib_deps =
    autowp/MCP2515 @ ^1.2.1
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
upload_flags =
    --before=default_reset
    --after=hard_reset
